import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Call from '@/components/Call';

export default function About() {
  return (
    <div className='bg-gray-900'> 
    <Head>
    <title>About | Rent a Car</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type='png' href='/img/car.png' />
  </Head>
    <section id='about' className='w-full pt-20 flex h-screen items-center justify-center opacity-90' >
      <div className='text-center text-white'>
        <p className='text-3xl md:text-4xl xl:text-6xl font-bold'>About Our Company</p>
        <Link href='/Contact' className='mt-8 inline-block py-3 px-6 text-xl xl:text-3xl font-bold text-gray-800 border-2  bg-purple-600 border-purple-600 rounded-lg hover:scale-110 duration-200'>Rent a Car!</Link>
      </div>
    </section>
    <div className='w-full h-full items-center mt-5 mb-16'>
        <h1 className='text-3xl md:text-5xl lg:text-6xl xl:text-6xl text-center text-purple-600 mb-6 mt-6 md:mt-16 md:mb-16 font-bold'>About Our Company</h1>
        <div className='mr-6 ml-6 md:ml-44 md:mr-44'>
        <div className='text-lg md:text-xl xl:text-2xl text-slate-500 font-medium mr-5 ml-5'>
        <p className='mt-3 mb-6'>Welcome to 'Rent a Car' where we strive to provide you with the best possible rental car experience. We understand that renting a car can be a stressful experience, so we work hard to make the process as simple and hassle-free as possible.</p>

        <p className='mb-6'>Our company was founded on the belief that everyone should have access to reliable and affordable transportation. We want to give you the opportunity to experience wonderful, unusual driving experiences with the best sports cars at an affordable price. We are committed to providing our customers with a wide variety of sport vehicles to choose from..</p>

        <p className='mb-6'>At 'Rent a Car', we pride ourselves on our exceptional customer service. Our team of experienced professionals is dedicated to ensuring that your rental experience is smooth and enjoyable from start to finish. Whether you need a car for a day, a week, or longer, we are here to help.</p>

        <p className='mb-6'>We believe that transparency is key, which is why we are upfront about our pricing and policies. We want our customers to feel confident in their rental decisions, and we are always available to answer any questions you may have.</p>

        <p className='mb-6'>Thank you for considering 'Rent a Car' for your transportation needs. We look forward to serving you soon!</p>
        </div>
        </div>
      </div>
      <section className='w-full flex mb-5 md:mt-16 xl:mt-16'>
      <div className='w-full justify-center text-center md:mt-6'>
      <hr className="w-1/2 mx-auto h-0.5 bg-white mb-3"></hr>
      <h1 className='text-2xl font-bold md:text-3xl lg:text-4xl xl:text-5xl text-purple-600'>OUR OFFER</h1>
      <div className='text-slate-500 font-medium text-xl md:text-xl lg:text-2xl xl:text-2xl'>
      <p className='mt-6'>A wide selection of cars</p>
      <p className='mt-6'>Cars from different parts of the country</p>
      <p className='mt-6'>Possibility of short or long term rental</p>
      <p className='mt-6'>Attractive prices and discounts</p>
      <p className='mt-6'>Unforgettable experiences</p>
      </div>
      <Link href='/Offer'>
        <button className="bg-purple-600 border-purple-600 rounded-lg hover:scale-110 duration-200 text-gray-900 text-lg font-semibold p-1 mt-6 xl:text-2xl mb-3 h-10 xl:h-14">See the full offer!</button> 
      </Link>
      <hr className="w-1/2 mx-auto h-0.5 bg-white mt-6 mb-3"></hr>
      </div>
    </section>
    <Call/>
    </div>
  )
}
