import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { MdPhoneCallback } from 'react-icons/md';
import { HiOutlineMail } from 'react-icons/hi';

export default function Contact() {

    const [name, setName] = useState('');
    const [lastName, setLastName] = useState('');
    const [email, setEmail] = useState('');
    const [number, setNumber] = useState('');
    const [message, setMessage] = useState('');

    const handleSubmit = (event) => {
        event.preventDefault();

    setName("");
    setLastName("");
    setEmail("");
    setNumber("");
    setMessage("");
  };

  return (
    <div className='bg-gray-900'>
    <Head>
    <title>Contact | Rent a Car</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type='png' href='/img/car.png'/>
  </Head>
    <section id='contact' className='w-full pt-20 flex h-screen items-center justify-center opacity-90'>
      <div className='text-center text-white'>
        <p className='text-3xl md:text-4xl xl:text-6xl font-bold'>Contact Us</p>
        <Link href='' className='mt-8 inline-block py-3 px-6 text-xl xl:text-3xl font-bold text-gray-800 border-2 bg-purple-600 border-purple-600 rounded-lg hover:scale-110 duration-200'>Write a message or call!</Link>
      </div>
    </section>
    <section className="w-full h-full">
      <h1 className="text-3xl md:text-5xl lg:text-6xl xl:text-6xl text-center text-purple-600 mb-6 mt-6 md:mt-16 md:mb-16 font-bold">Contact Us</h1>
      <div className='grid md:grid-cols-2 md:mr-52 md:ml-52 xl:mr-72 xl:ml-72'>
      <div className='text-center w-full md:w-80 text-purple-600 md:text-left text-lg xl:text-xl pl-3 pr-3'>
        <p className='ml-3 mb-2 md:mt-5'>Rent a Car</p>
        <p className='ml-3 mb-2'>1234 1st Ave</p>
        <p className='ml-3 mb-2'>Seattle, WA 98101</p>
        <p className='ml-3 mb-2'>NIP 0000 111 455757</p>
        <p className='ml-3 mb-2 flex'><MdPhoneCallback size={25}  className='mr-3 ml-24 md:ml-0'/>999-888-444</p>
        <p className='ml-3 mb-2 flex'><HiOutlineMail size={25}  className='mr-3 ml-12 md:ml-0'/>rentcarcompany@gmail.com</p>
        <p className='ml-3 mb-2'>We operate stationary in This City.</p>
        <p className='ml-3 mb-2'>Open from Monday to Friday from 9:00 to 18:00</p>
        <p className='ml-3 mb-2'>Saturday and Sunday: contact by phone or e-mail.</p>
      </div>
      <form id='form' onSubmit={handleSubmit} className="w-full mt-5 p-10 pt-4 md:p-0 md:pt-0">
      <hr className="w-1/2 mx-auto h-0.5 bg-white mb-6 md:hidden"></hr>
        <p  className='text-center md:text-left text-purple-600 text-xl md:text-2xl xl:text-4xl mb-3'>Contact form</p>
        <div className='grid md:grid-cols-2'>
        <div className="mb-4 md:mr-3">
          <label htmlFor="name" className="block text-purple-600 font-bold xl:text-2xl mb-2"></label>
          <input
            type="text"
            id="name"
            name="name"
            placeholder='Name'
            value={name}
            onChange={(e) => setName(e.target.value)}
            className="shadow appearance-none border rounded w-full py-1 px-3 text-purple-600 leading-tight focus:outline-none focus:shadow-outline"
            required/>
        </div>
        <div className="mb-4">
          <label htmlFor="lastname" className="block text-purple-600 font-bold xl:text-2xl mb-2"></label>
          <input
            type="text"
            id="LastName"
            name="LastName"
            placeholder='Last Name'
            value={lastName}
            onChange={(e) => setLastName(e.target.value)}
            className="shadow appearance-none border rounded w-full py-1 px-3 text-purple-600 leading-tight focus:outline-none focus:shadow-outline"
            required/>
        </div>
        </div>
        <div className='grid md:grid-cols-2'>
        <div className="mb-4 md:mr-3">
          <label htmlFor="email" className="block text-purple-600 font-bold xl:text-2xl mb-2"></label>
          <input
            type="email"
            id="email"
            name="email"
            placeholder='Email'
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="shadow appearance-none border rounded w-full py-1 px-3 text-purple-600 leading-tight focus:outline-none focus:shadow-outline"
            required/>
        </div>
        <div className="mb-4">
          <label htmlFor="number" className="block text-purple-600 font-bold xl:text-2xl mb-2"></label>
          <input
            type='number'
            id="number"
            name="number"
            placeholder='Number'
            value={number}
            onChange={(e) => setNumber(e.target.value)}
            className="shadow appearance-none border rounded w-full py-1 px-3 text-purple-600 leading-tight focus:outline-none focus:shadow-outline"
            required/>
        </div>
        </div>
        <div className="mb-4">
            <label htmlFor="cars" className="block mb-2 text-sm font-medium text-gray-500"></label>
                <select id="cars" className="shadow appearance-none border text-gray-500 text-xs md:text-sm rounded focus:outline-none focus:shadow-outline block w-48 py-1 px-3" defaultValue="default">
                <option value="default" disabled>Select a car</option>
                <option value="DHC">Dodge Challenger SRT</option>
                <option value="MGT">Ford Mustang GT</option>
                <option value="MGTR">Ford Mustang GT Roush</option>
                <option value="MAMG">Mercedes-Benz A45 AMG</option>
                <option value="SVJ">Lamborghini Aventador SVJ</option>
                <option value="SUP">Toyota GR Supra</option>
                <option value="P4S">Porsche 911 Carrera 4S</option>
                </select>
                </div>
        <div className="mb-4">
          <label htmlFor="message" className="block text-purple-600 font-bold xl:text-2xl mb-2"></label>
          <textarea
            id="message"
            name="message"
            placeholder='Message'
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            className="shadow appearance-none border rounded w-full py-1 px-3 text-purple-600 leading-tight focus:outline-none focus:shadow-outline h-32"
            required/>
        </div>
        <div className="flex justify-center">
          <button
            type="submit"
            className="bg-purple-600 border-purple-600 rounded-lg hover:scale-110 duration-200 text-gray-800 text-lg font-semibold p-1 xl:text-2xl mb-3 h-10 xl:h-14"> Send Message</button>
        </div>
      </form>
      </div>
    </section>
    </div>
  );
};
