import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Plan from '@/components/Plan';
import Cars3d from '@/components/Cars3d';
import Call from '@/components/Call';
import Interested from '@/components/Interested';
import { BsChevronCompactLeft, BsChevronCompactRight } from 'react-icons/bs';
import { RxDotFilled } from 'react-icons/rx';

export default function HomePage() {

  const slides = [
  {
    url: '/main_view/dodge.jpg',
  },
  {
    url: '/main_view/gt.jpg',
  },
  {
    url: '/main_view/roush.jpg',
  },
  {
    url: '/main_view/merc.jpg',
  },
  {
    url: '/main_view/lam.jpg',
  },
  {
    url: '/main_view/sup.jpg',
  },
  {
    url: '/main_view/porsche.png',
  },
  ];

  const [currentIndex, setCurrentIndex] = useState(0);

  const prevSlide = () => {
    const isFirstSlide = currentIndex === 0;
    const newIndex = isFirstSlide ? slides.length - 1 : currentIndex - 1;
    setCurrentIndex(newIndex);
  };

  const nextSlide = () => {
    const isLastSlide = currentIndex === slides.length - 1;
    const newIndex = isLastSlide ? 0 : currentIndex + 1;
    setCurrentIndex(newIndex);
  };

  const goToSlide = (slideIndex) => {
    setCurrentIndex(slideIndex);
  };

  return (
    <div className='bg-gray-900'>
    <Head>
        <title>Home | Rent a Car</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href='/img/car.png' />
      </Head>
    <section id='main' className='w-full pt-10 flex md:h-screen lg:h-screen xl:h-screen 2xl:h-screen'>
        <div className='max-w-[700px] h-[500px] w-full m-auto py-16 px-4'>
      <div
        style={{ backgroundImage: `url(${slides[currentIndex].url})`}}
        className='w-full h-full rounded-2xl bg-center bg-cover duration-500 z-10 flex flex-col justify-center items-center'>
    <p className='text-3xl text-center md:text-4xl xl:text-5xl font-bold text-white'>Welcome to the Rent Car website!</p>
    <Link href='#3d' className='mt-8 inline-block py-3 px-6 text-xl xl:text-3xl font-bold text-gray-800 border-2  bg-purple-600 border-purple-600 rounded-lg hover:scale-110 duration-200'>Check 3D models!</Link>
      </div>
      {/* Left Arrow */}
      <div className='hidden md:block absolute top-[50%] -translate-x-0 translate-y-[-50%] left-44 xl:left-96 text-2xl rounded-full p-2 text-purple-600 cursor-pointer'>
        <BsChevronCompactLeft onClick={prevSlide} size={40} />
      </div>
      {/* Right Arrow */}
      <div className='hidden md:block absolute top-[50%] -translate-x-0 translate-y-[-50%] right-44 xl:right-96 text-2xl rounded-full p-2 text-purple-600 cursor-pointer'>
        <BsChevronCompactRight onClick={nextSlide} size={40} />
      </div>
      <div className='flex top-4 justify-center py-2'>
        {slides.map((slide, slideIndex) => (
          <div
            key={slideIndex}
            onClick={() => goToSlide(slideIndex)}
            className='text-2xl cursor-pointer text-purple-600'>
            <RxDotFilled/>
          </div>
        ))}
      </div>
    </div>
    </section>
    <section className='w-full pt-8 md:pt-20 flex'>
      <div className='w-full justify-center text-center text-slate-500'>
      <hr className="w-1/2 mx-auto h-0.5 bg-white mb-3"></hr>
      <h1 className='text-xl font-bold md:text-3xl lg:text-4xl md:mt-6 uppercase text-purple-600'>Rich Offer</h1>
      <h2 className='text-xl font-bold md:text-3xl lg:text-4xl mt-2 md:mt-6 uppercase text-purple-600'>A wide range of cars</h2>
      <h3 className='text-xl font-medium md:text-2xl lg:text-3xl xl:text-3xl mr-6 ml-6 md:mr-24 lg:mr-24 xl:mr-24 md:ml-24 lg:ml-24 xl:ml-24 mt-2 md:mt-6'>A wide selection of cars from different parts of the country. Possibility of short or long term rental.</h3>
      <p className='text-xl font-medium md:text-2xl lg:text-3xl xl:text-3xl mt-2 md:mt-6'>We offer attractive prices and unforgettable experiences!</p>
      <Link href='/Offer'><button className='mt-8 inline-block py-3 px-6 text-xl xl:text-3xl font-bold text-gray-800 border-2 bg-purple-600 border-purple-600 rounded-lg hover:scale-110 duration-200 md:mb-4'>See the full offer!</button>
        </Link>
      </div>
    </section>
    <Plan/>
    <Call/>
    <Cars3d/>
    <Interested/>
    </div>
  )
}
