import Head from 'next/head';
import HomePage from './HomePage';

export default function Home() {
  return (
    <>
      <Head>
        <title>Rent a Car</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href='/img/car.png' />
      </Head>
      <HomePage/>
    </>
  );
};
