import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import Interested from '@/components/Interested';

export default function Rent() {
  return (
    <div className='bg-gray-900'>
    <Head>
    <title>Rental Conditions | Rent a Car</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type='png' href='/img/car.png' />
  </Head>
    <section id='rent' className='w-full pt-20 flex h-screen items-center justify-center opacity-90' >
      <div className='text-center text-white'>
        <p className='text-3xl md:text-4xl xl:text-6xl font-bold'>Our Rental Conditions</p>
        <Link href='/Contact' className='mt-8 inline-block py-3 px-6 text-xl xl:text-3xl font-bold text-gray-800 border-2  bg-purple-600 border-purple-600 rounded-lg hover:scale-110 duration-200'>Rent a Car!</Link>
      </div>
    </section>
    <section className='w-full h-full items-center mt-5'>
        <h1 className='text-3xl md:text-5xl lg:text-6xl xl:text-6xl text-center text-purple-600 mb-6 mt-6 md:mt-16 md:mb-16 font-bold'>General Rental Conditions</h1>
        <div className='mr-10 ml-10 md:ml-44 md:mr-44 mb-16'>
        <div className='text-lg md:text-xl xl:text-2xl text-slate-500 mr-5 ml-5 text-center md:text-left font-medium'>
        <h1 className='mt-4'>At 'Rent a Car', we want to ensure that all of our customers have a clear understanding of our rental conditions. Please take a moment to review the following terms and conditions:</h1>
        <h1 className='text-center mt-6 mb-6 text-purple-600'>§ 1 Driver Requirements:</h1>
        <p>All drivers must be at least 21 years of age and hold a valid driver's license. Some vehicles may require drivers to be at least 25 years old. An additional fee may apply for drivers under the age of 25.</p>
        <h1 className='text-center mt-6 mb-6 text-purple-600'>§ 2 Rental Period:</h1>
        <p>The minimum rental period is one day (24 hours). We offer flexible rental periods, and our team will work with you to find a rental period that meets your needs.</p>
        <h1 className='text-center mt-6 mb-6 text-purple-600'>§ 3 Payment:</h1>
        <p>We accept all major credit cards and cash payments. A security deposit may be required at the time of rental.</p>
        <h1 className='text-center mt-6 mb-6 text-purple-600'>§ 4 Insurance:</h1>
        <p>All of our vehicles are covered by comprehensive insurance. The renter is responsible for a deductible in case of damage or theft of the vehicle. Optional insurance upgrades are available for purchase at the time of rental.</p>
        <h1 className='text-center mt-6 mb-6 text-purple-600'>§ 5 Fuel:</h1>
        <p>All vehicles are provided with a full tank of gas at the time of rental. The renter is responsible for returning the vehicle with a full tank of gas. If the vehicle is returned with less than a full tank, the renter will be charged for the cost of refueling.</p>
        <h1 className='text-center mt-6 mb-6 text-purple-600'>§ 6 Additional Drivers:</h1>
        <p>Additional drivers can be added to the rental agreement for an additional fee. All additional drivers must meet our driver requirements and be listed on the rental agreement.</p>
        <h1 className='text-center mt-6 mb-6 text-purple-600'>§ 7 Restrictions:</h1>
        <p>Our vehicles cannot be taken outside of the state or country without prior written permission from 'Rent a Car'. Vehicles must be driven on paved roads only and must not be used for racing, towing, or off-roading.</p>

        <h2>Thank you for choosing 'Rent a Car' for your transportation needs. If you have any questions or concerns about our rental conditions, please don't hesitate to contact us. We are always here to help.</h2>
        </div>
        </div>
      </section>
      <hr className="w-1/2 mx-auto h-0.5 bg-white mb-6"></hr>
      <Interested/>
    </div>
  );
};
