/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 amgDraco.gltf --transform
Author: Lexyc16 (https://sketchfab.com/Lexyc16)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mercedes-benz-a45-amg-2018-9482f251f9c34a6e91d7777db5934cfc
Title: Mercedes-Benz A45 AMG 2018
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3dglb/mercamg.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments geometry={nodes.Object_6.geometry} material={materials['Material.014']} />
        <lineSegments geometry={nodes.Object_7.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.037']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_33.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_37.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Object_46.geometry} material={materials['Material.042']} />
      </group>
    </group>
  )
}

useGLTF.preload('/3dglb/mercamg.glb')
