/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 gtDraco.gltf --transform
Author: samsidparty (https://sketchfab.com/samsidparty)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ford-mustang-gt-5a3215daf55947fb9836daaff69f49ae
Title: Ford Mustang GT
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3dglb/mustanggt.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.014}>
          <group position={[-0.81, 0.35, -1.26]} rotation={[Math.PI, 0, -3.12]}>
            <mesh geometry={nodes.Wheel_RR_Rubber_0.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Wheel_RR_MetalDark_0.geometry} material={materials.MetalDark} />
            <mesh geometry={nodes.Wheel_RR_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group position={[-0.8, 0.35, 1.44]} rotation={[Math.PI, 0, -3.12]}>
            <mesh geometry={nodes.Wheel_FR_Rubber_0.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Wheel_FR_MetalDark_0.geometry} material={materials.MetalDark} />
            <mesh geometry={nodes.Wheel_FR_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group position={[0.81, 0.35, -1.26]} rotation={[0, 0, 0.03]}>
            <mesh geometry={nodes.Wheel_RL_Rubber_0.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Wheel_RL_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Wheel_RL_MetalDark_0.geometry} material={materials.MetalDark} />
          </group>
          <group position={[0.8, 0.35, 1.44]} rotation={[0, 0, 0.03]}>
            <mesh geometry={nodes.Wheel_FL_Rubber_0.geometry} material={materials.Rubber} />
            <mesh geometry={nodes.Wheel_FL_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Wheel_FL_MetalDark_0.geometry} material={materials.MetalDark} />
          </group>
          <group position={[0, 0.17, 0]}>
            <mesh geometry={nodes.FordMustangGT_LOD0_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.FordMustangGT_LOD0_Metal_0_1.geometry} material={materials.Metal} />
            <mesh geometry={nodes.FordMustangGT_LOD0_Glass_0.geometry} material={materials.Glass} />
            <mesh geometry={nodes.FordMustangGT_LOD0_RedLight_0.geometry} material={materials.RedLight} />
            <mesh geometry={nodes.FordMustangGT_LOD0_TurnSignal_0.geometry} material={materials.TurnSignal} />
            <mesh geometry={nodes.FordMustangGT_LOD0_CarbonFiber_0.geometry} material={materials.CarbonFiber} />
            <mesh geometry={nodes.FordMustangGT_LOD0_Paint_0.geometry} material={materials.Paint} />
            <mesh geometry={nodes.FordMustangGT_LOD0_WhiteLight_0.geometry} material={materials.WhiteLight} />
            <mesh geometry={nodes.FordMustangGT_LOD0_Interior_0.geometry} material={materials.Interior} />
            <mesh geometry={nodes.FordMustangGT_LOD0_Base_0.geometry} material={materials.CarbonFiber} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dglb/mustanggt.glb')
