/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hellcatDraco.gltf --transform
Author: preslav.petkov0606 (https://sketchfab.com/preslav.petkov0606)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dodge-challenger-srt-hellcat-2015-94208b77d32a4934afd88f52615fd4b8
Title: Dodge Challenger SRT Hellcat 2015
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3dglb/dodgehellcat.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.45, 0, -Math.PI / 2]} scale={[0.23, 0.02, 0.03]}>
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Material.032']} />
      </group>
      <group position={[0.83, 0.42, -1.01]} rotation={[2.65, 0, -Math.PI / 2]} scale={[0.23, 0.02, 0.03]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.032']} />
      </group>
      <group position={[0.83, 0.36, -1.12]} rotation={[1.08, -0.02, -1.56]} scale={[-0.34, 0.34, 0.34]}>
        <mesh geometry={nodes.Object_18.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['1_car_paint.006']} />
      </group>
      <group rotation={[-1.12, -0.02, -1.56]} scale={[-0.34, 0.34, 0.34]}>
        <mesh geometry={nodes.Object_26.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials['1_car_paint.006']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['1_car_paint.006']} />
      </group>
      <group position={[0.75, 0.73, 2.51]} rotation={[Math.PI / 2, 0, 0]} scale={0.09}>
        <mesh geometry={nodes.Object_38.geometry} material={materials.Clear} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Exhaust} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.EmissionWhite} />
      </group>
      <group position={[0.58, 0.73, 2.52]} rotation={[Math.PI / 2, 0, 0]} scale={0.08}>
        <mesh geometry={nodes.Object_42.geometry} material={materials.Exhaust} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.EmissionWhite} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Clear} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Material.001']} />
      </group>
      <group position={[0, 1.48, 0]}>
        <mesh geometry={nodes.Object_49.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.Window} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.VoidFenders} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.FuelCap} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.FuelCap} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.FuelCap} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.Exhaust} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.Clear} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.ClearRed} />
        <mesh geometry={nodes.Object_61.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0, 1.48, 0]}>
        <mesh geometry={nodes.Object_69.geometry} material={materials['Metal_-_Chrome_-_Rough_0.2']} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.Body} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['1_car_paint.005']} position={[0.89, 0.42, -1]} rotation={[2.65, 0, -Math.PI / 2]} scale={[0.23, 0.02, 0.03]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['1_car_paint.005']} rotation={[0.45, 0, -Math.PI / 2]} scale={[0.23, 0.02, 0.03]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['Material.024']} position={[0.88, 0.36, -1.12]} rotation={[2.19, 0, 3.1]} scale={[-1.64, 1.43, 1.43]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Material.024']} rotation={[-0.01, 0, 3.1]} scale={[-1.64, 1.43, 1.43]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.LogosAndText} position={[-0.51, 0.77, 2.46]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0, 0]} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.GrilleBack} position={[0, 1.48, 0]} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.GrilleBack} position={[0, 0.73, 2.53]} rotation={[Math.PI / 2, 0, 0]} scale={0.08} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Body} position={[0, 1.48, 0]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.LogosAndText} position={[0, 1.48, 0]} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Wheel} position={[0, 1.48, 0]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.emissionRed} position={[0, 1.48, 0]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.LogosAndText} position={[0.97, 0.72, 1.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.03} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.DODGElogoBack} position={[0.3, 0.7, 2.6]} rotation={[Math.PI / 2, 0, -0.07]} scale={0.06} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.DODGElogoBack} position={[0.42, 0.7, 2.6]} rotation={[1.53, 0, -0.09]} scale={0.02} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.DODGElogoBack} position={[-0.52, 1.05, -2.09]} rotation={[1.39, 0.03, 3.04]} scale={0.05} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.DODGElogoBack} position={[-0.61, 1.05, -2.09]} rotation={[1.43, 0, 3.03]} scale={0.02} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.LogosAndText} position={[0.4, 0.97, 1.99]} rotation={[-1.44, 0.19, -1.34]} scale={0} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.LogosAndText} position={[-0.16, 1.01, 2.17]} rotation={[0, 0, -Math.PI / 2]} scale={0} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.LogosAndText} position={[-0.75, 0.43, 2.28]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0, 0]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.GrilleBack} position={[0, 0.37, 2.36]} rotation={[Math.PI / 2, 0, 0]} scale={[0.1, 0.08, 0.11]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.DODGElogoBack} position={[0, 0.9, -2.08]} rotation={[1.83, 0, Math.PI]} scale={[0.07, 0.08, 0.05]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.GrilleBack} position={[0, 0.2, 0]} rotation={[0.01, 0, 0]} scale={[0.78, 0.78, 1.39]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.GrilleBack} position={[0, 0.83, 0]} rotation={[-0.01, 0, Math.PI]} scale={[0.78, 0.78, 1.39]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Exhaust} />
      <mesh geometry={nodes.Object_100.geometry} material={materials['Material.003']} position={[0.93, 0.36, 1.82]} scale={0.21} />
      <mesh geometry={nodes.Object_102.geometry} material={materials['Material.004']} position={[0.91, 0.36, 1.82]} rotation={[Math.PI / 2, 0, -1.64]} scale={0.02} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Wheel} position={[0.93, 0.36, 1.82]} scale={0.21} />
      <mesh geometry={nodes.Object_106.geometry} material={materials.Tire} position={[0.79, 0.36, 1.82]} scale={[1.09, 1.07, 1.07]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials['Material.003']} position={[-0.93, 0.36, 1.82]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.21} />
      <mesh geometry={nodes.Object_110.geometry} material={materials['Material.004']} position={[-0.91, 0.36, 1.83]} rotation={[Math.PI / 2, 0, 1.5]} scale={0.02} />
      <mesh geometry={nodes.Object_112.geometry} material={materials.Wheel} position={[-0.93, 0.36, 1.82]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.21} />
      <mesh geometry={nodes.Object_114.geometry} material={materials.Tire} position={[-0.79, 0.36, 1.82]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.09, 1.07, 1.07]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials['Material.003']} position={[0.94, 0.36, -1.13]} scale={0.21} />
      <mesh geometry={nodes.Object_118.geometry} material={materials['Material.004']} position={[0.92, 0.36, -1.14]} rotation={[Math.PI / 2, 0, -1.64]} scale={0.02} />
      <mesh geometry={nodes.Object_120.geometry} material={materials.Wheel} position={[0.94, 0.36, -1.13]} scale={0.21} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.Tire} position={[0.79, 0.36, -1.13]} scale={[1.09, 1.07, 1.07]} />
      <mesh geometry={nodes.Object_124.geometry} material={materials['Material.003']} position={[-0.93, 0.36, -1.13]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.21} />
      <mesh geometry={nodes.Object_126.geometry} material={materials['Material.004']} position={[-0.91, 0.36, -1.12]} rotation={[Math.PI / 2, 0, 1.5]} scale={0.02} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.Wheel} position={[-0.93, 0.36, -1.13]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.21} />
      <mesh geometry={nodes.Object_130.geometry} material={materials.Tire} position={[-0.79, 0.36, -1.13]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.09, 1.07, 1.07]} />
    </group>
  )
}

useGLTF.preload('/3dglb/dodgehellcat.glb')
