/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 svj5.gltf --transform
Author: SDC PERFORMANCE™️ (https://sketchfab.com/3Duae)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/aventador-svj-infinitytm-2b46e077b12b41cd96b6c57f8f54be89
Title: Aventador SVJ Infinity™️
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/3dglb/lambosvj.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.Body_CARBONE_0.geometry} material={materials.CARBONE} />
        <mesh geometry={nodes.Body_CARROSSERIE_0.geometry} material={materials.CARROSSERIE} />
        <mesh geometry={nodes.Body_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.Body_Undercarriage_0.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Body_Chrome_0.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Body_GlassLights_0.geometry} material={materials.GlassLights} />
        <mesh geometry={nodes.Body_Aluminum_0.geometry} material={materials.Aluminum} />
        <mesh geometry={nodes.Body_MetalDark_0.geometry} material={materials.MetalDark} />
        <mesh geometry={nodes.Body_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Body_Material013_0.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Body_MetalExhaustTextured_0.geometry} material={materials.MetalExhaustTextured} />
        <mesh geometry={nodes.Body_ExteriorDetailTex_0.geometry} material={materials.ExteriorDetailTex} />
        <mesh geometry={nodes.Body_intTexButtonsGlossy_0.geometry} material={materials.intTexButtonsGlossy} />
        <mesh geometry={nodes.Body_Material003_0.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Body_Material002_0.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Body_Material001_0.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Body_Material011_0.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Body_intPlasticDkPlain_0.geometry} material={materials.intPlasticDkPlain} />
        <mesh geometry={nodes.Body_intAlcantara_0.geometry} material={materials.intAlcantara} />
        <mesh geometry={nodes.Body_MetalGoldenLogo_0.geometry} material={materials.MetalGoldenLogo} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.DoorFrLeft_GLASS_0.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.DoorFrLeft_Chrome_0.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.DoorFrLeft_CARBONE_0.geometry} material={materials.CARBONE} />
        <mesh geometry={nodes.DoorFrLeft_CARROSSERIE_0.geometry} material={materials.CARROSSERIE} />
      </group>
      <group position={[0, 109.83, -61.62]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.EngineHood_MetalDark_0.geometry} material={materials.MetalDark} />
        <mesh geometry={nodes.EngineHood_Undercarriage_0.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.EngineHood_CARBONE_0.geometry} material={materials.CARBONE} />
        <mesh geometry={nodes.EngineHood_Material009_0.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.EngineHood_GLASS_0.geometry} material={materials.GLASS} />
      </group>
      <group position={[0, 10.26, -0.63]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.Headlights_LightEmissiveWhite_0.geometry} material={materials.LightEmissiveWhite} />
        <mesh geometry={nodes.Headlights_CARBONE_0.geometry} material={materials.CARBONE} />
        <mesh geometry={nodes.Headlights_Chrome_0.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Headlights_GlassLights_0.geometry} material={materials.GlassLights} />
        <mesh geometry={nodes.Headlights_MetalExhaustTextured_0.geometry} material={materials.MetalExhaustTextured} />
        <mesh geometry={nodes.Headlights_HdLightsLens_0.geometry} material={materials.HdLightsLens} />
      </group>
      <group position={[0.2, 9.83, -1.2]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.Taillights_Chrome_0.geometry} material={materials.Chrome} />
        <mesh geometry={nodes.Taillights_Aluminum_0.geometry} material={materials.Aluminum} />
        <mesh geometry={nodes.Taillights_CARBONE_0.geometry} material={materials.CARBONE} />
        <mesh geometry={nodes.Taillights_MetalDark_0.geometry} material={materials.MetalDark} />
        <mesh geometry={nodes.Taillights_GlassRedLights_0.geometry} material={materials.GlassRedLights} />
        <mesh geometry={nodes.Taillights_GlassLights_0.geometry} material={materials.GlassLights} />
        <mesh geometry={nodes.Taillights_GLS_MR_0.geometry} material={materials.GLS_MR} />
        <mesh geometry={nodes.Taillights_GlassOrangeLights_0.geometry} material={materials.GlassOrangeLights} />
        <mesh geometry={nodes.Taillights_GlassWhite_0.geometry} material={materials.GlassWhite} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.Body003_CARBONE_0.geometry} material={materials.CARBONE} />
        <mesh geometry={nodes.Body003_Material010_0.geometry} material={materials['Material.010']} />
      </group>
      <group position={[0, 62.94, -41.29]} rotation={[-Math.PI / 2, 0, 0]} scale={162.09}>
        <mesh geometry={nodes.Circle_Turbo_0.geometry} material={materials.Turbo} />
        <mesh geometry={nodes.Circle_Turbo_R_0.geometry} material={materials.Turbo_R} />
        <mesh geometry={nodes.Circle_black001_0.geometry} material={materials.Undercarriage} />
        <mesh geometry={nodes.Circle_FEr_0.geometry} material={materials.material} />
        <mesh geometry={nodes.Circle_B_fer_0.geometry} material={materials.B_fer} />
        <mesh geometry={nodes.Circle_Material017_0.geometry} material={materials['Material.017']} />
      </group>
      <group position={[99.86, 38.27, -144.92]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={46.79}>
        <group position={[0.14, 0.24, 0.06]} rotation={[-0.61, 0, -Math.PI]} scale={[0.16, 0.19, 0.19]}>
          <mesh geometry={nodes['<Wheel_CRBN_JANTE_0'].geometry} material={materials.CRBN_JANTE} />
          <mesh geometry={nodes['<Wheel_Material023_0'].geometry} material={materials['Material.023']} />
          <mesh geometry={nodes['<Wheel_Material025_0'].geometry} material={materials['Material.025']} />
          <mesh geometry={nodes['<Wheel_Material024_0'].geometry} material={materials['Material.024']} />
          <mesh geometry={nodes['<Wheel_pneu005_0'].geometry} material={materials['pneu.005']} />
          <mesh geometry={nodes['<Wheel_PZEO_0'].geometry} material={materials.PZEO} />
        </group>
        <group scale={0.16}>
          <mesh geometry={nodes.Circle002_BLUE_0.geometry} material={materials.BLUE} />
          <mesh geometry={nodes.Circle002_BLACK_0.geometry} material={materials.BLACK} />
        </group>
        <group scale={0.54}>
          <mesh geometry={nodes.Circle004_plaquette_de_frein002_0.geometry} material={materials['plaquette_de_frein.002']} />
          <mesh geometry={nodes.Circle004_visse002_0.geometry} material={materials['visse.002']} />
        </group>
        <mesh geometry={nodes['<Wheel001_CRBN_JANTE_0'].geometry} material={materials.CRBN_JANTE} position={[0.14, 0.24, 0.06]} rotation={[-0.61, 0, -Math.PI]} scale={[0.16, 0.19, 0.19]} />
        <mesh geometry={nodes['<Wheel002_Material018_0'].geometry} material={materials['Material.018']} rotation={[0, 0.61, Math.PI / 2]} scale={[2.75, 3.22, 3.22]} />
        <mesh geometry={nodes.Circle005_CABON_0.geometry} material={materials.CABON} scale={0.16} />
        <mesh geometry={nodes.Circle001_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
        <mesh geometry={nodes.Circle003_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
        <mesh geometry={nodes.Plane001_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
      </group>
      <group position={[-100.62, 38.27, -144.24]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={46.79}>
        <group position={[0.14, 0.24, 0.06]} rotation={[-0.61, 0, -Math.PI]} scale={[0.16, 0.19, 0.19]}>
          <mesh geometry={nodes['<Wheel003_CRBN_JANTE_0'].geometry} material={materials.CRBN_JANTE} />
          <mesh geometry={nodes['<Wheel003_Material023_0'].geometry} material={materials['Material.023']} />
          <mesh geometry={nodes['<Wheel003_Material025_0'].geometry} material={materials['Material.025']} />
          <mesh geometry={nodes['<Wheel003_Material024_0'].geometry} material={materials['Material.024']} />
          <mesh geometry={nodes['<Wheel003_pneu005_0'].geometry} material={materials['pneu.005']} />
          <mesh geometry={nodes['<Wheel003_PZEO_0'].geometry} material={materials.PZEO} />
        </group>
        <group scale={0.16}>
          <mesh geometry={nodes.Circle008_BLUE_0.geometry} material={materials.BLUE} />
          <mesh geometry={nodes.Circle008_BLACK_0.geometry} material={materials.BLACK} />
        </group>
        <group scale={0.54}>
          <mesh geometry={nodes.Circle010_plaquette_de_frein002_0.geometry} material={materials['plaquette_de_frein.002']} />
          <mesh geometry={nodes.Circle010_visse002_0.geometry} material={materials['visse.002']} />
        </group>
        <mesh geometry={nodes['<Wheel004_CRBN_JANTE_0'].geometry} material={materials.CRBN_JANTE} position={[0.14, 0.24, 0.06]} rotation={[-0.61, 0, -Math.PI]} scale={[0.16, 0.19, 0.19]} />
        <mesh geometry={nodes['<Wheel005_Material018_0'].geometry} material={materials['Material.018']} rotation={[0, 0.61, Math.PI / 2]} scale={[2.75, 3.22, 3.22]} />
        <mesh geometry={nodes.Circle006_CABON_0.geometry} material={materials.CABON} scale={0.16} />
        <mesh geometry={nodes.Circle007_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
        <mesh geometry={nodes.Circle009_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
        <mesh geometry={nodes.Plane002_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
      </group>
      <group position={[-100.62, 32.03, 126.85]} rotation={[-Math.PI / 2, 0, -1.23]} scale={40.05}>
        <group position={[0.14, 0.24, 0.06]} rotation={[-0.61, 0, -Math.PI]} scale={[0.16, 0.19, 0.19]}>
          <mesh geometry={nodes['<Wheel006_CRBN_JANTE_0'].geometry} material={materials.CRBN_JANTE} />
          <mesh geometry={nodes['<Wheel006_Material023_0'].geometry} material={materials['Material.023']} />
          <mesh geometry={nodes['<Wheel006_Material025_0'].geometry} material={materials['Material.025']} />
          <mesh geometry={nodes['<Wheel006_Material024_0'].geometry} material={materials['Material.024']} />
          <mesh geometry={nodes['<Wheel006_pneu005_0'].geometry} material={materials['pneu.005']} />
          <mesh geometry={nodes['<Wheel006_PZEO_0'].geometry} material={materials.PZEO} />
        </group>
        <group scale={0.16}>
          <mesh geometry={nodes.Circle013_BLUE_0.geometry} material={materials.BLUE} />
          <mesh geometry={nodes.Circle013_BLACK_0.geometry} material={materials.BLACK} />
        </group>
        <group scale={0.54}>
          <mesh geometry={nodes.Circle015_plaquette_de_frein002_0.geometry} material={materials['plaquette_de_frein.002']} />
          <mesh geometry={nodes.Circle015_visse002_0.geometry} material={materials['visse.002']} />
        </group>
        <mesh geometry={nodes['<Wheel007_CRBN_JANTE_0'].geometry} material={materials.CRBN_JANTE} position={[0.14, 0.24, 0.06]} rotation={[-0.61, 0, -Math.PI]} scale={[0.16, 0.19, 0.19]} />
        <mesh geometry={nodes['<Wheel008_Material018_0'].geometry} material={materials['Material.018']} rotation={[0, 0.61, Math.PI / 2]} scale={[2.75, 3.22, 3.22]} />
        <mesh geometry={nodes.Circle011_CABON_0.geometry} material={materials.CABON} scale={0.16} />
        <mesh geometry={nodes.Circle012_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
        <mesh geometry={nodes.Circle014_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
        <mesh geometry={nodes.Plane003_BLACK_0.geometry} material={materials.BLACK} scale={0.16} />
      </group>
      <group position={[99.58, 32.03, 115.71]} rotation={[-Math.PI / 2, 0, 1.96]} scale={40.05}>
        <group position={[0.14, 0.24, 0.06]} rotation={[-0.61, 0, -Math.PI]} scale={[0.16, 0.19, 0.19]}>
          <mesh geometry={nodes['<Wheel011_CRBN_JANTE003_0'].geometry} material={materials.CRBN_JANTE} />
          <mesh geometry={nodes['<Wheel011_Material044_0'].geometry} material={materials['Material.023']} />
          <mesh geometry={nodes['<Wheel011_Material046_0'].geometry} material={materials['Material.025']} />
          <mesh geometry={nodes['<Wheel011_Material045_0'].geometry} material={materials['Material.024']} />
          <mesh geometry={nodes['<Wheel011_pneu008_0'].geometry} material={materials['pneu.008']} />
          <mesh geometry={nodes['<Wheel011_PZEO001_0'].geometry} material={materials.PZEO} />
        </group>
        <group scale={0.16}>
          <mesh geometry={nodes.Circle018_BLUE001_0.geometry} material={materials.BLUE} />
          <mesh geometry={nodes.Circle018_BLACK001_0.geometry} material={materials['BLACK.001']} />
        </group>
        <group scale={0.54}>
          <mesh geometry={nodes.Circle016_plaquette_de_frein004_0.geometry} material={materials['plaquette_de_frein.004']} />
          <mesh geometry={nodes.Circle016_visse004_0.geometry} material={materials['visse.002']} />
        </group>
        <mesh geometry={nodes['<Wheel010_CRBN_JANTE003_0'].geometry} material={materials.CRBN_JANTE} position={[0.14, 0.24, 0.06]} rotation={[-0.61, 0, -Math.PI]} scale={[0.16, 0.19, 0.19]} />
        <mesh geometry={nodes['<Wheel009_Material042_0'].geometry} material={materials['Material.018']} rotation={[0, 0.61, Math.PI / 2]} scale={[2.75, 3.22, 3.22]} />
        <mesh geometry={nodes.Circle020_CABON001_0.geometry} material={materials['CABON.001']} scale={0.16} />
        <mesh geometry={nodes.Circle019_BLACK001_0.geometry} material={materials['BLACK.001']} scale={0.16} />
        <mesh geometry={nodes.Circle017_BLACK001_0.geometry} material={materials['BLACK.001']} scale={0.16} />
        <mesh geometry={nodes.Plane004_BLACK001_0.geometry} material={materials['BLACK.001']} scale={0.16} />
      </group>
      <mesh geometry={nodes.Trunk_Material007_0.geometry} material={materials['Material.007']} position={[0, 75.54, 132.39]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Undercarriage_Undercarriage_0.geometry} material={materials.Undercarriage} position={[-0.01, 10.32, -0.65]} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Body002_Material008_0.geometry} material={materials['Material.008']} rotation={[-Math.PI / 2, 0, 0]} scale={0.1} />
    </group>
  )
}

useGLTF.preload('/3dglb/lambosvj.glb')
